name: task_7
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  mockito: ^5.4.4
  shared_preferences: ^2.0.11
  uuid: ^4.5.1
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  connectivity: ^3.0.6
  http: ^1.3.0
  build_runner: ^2.4.13
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
